---
name: Deploy to EC2

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  AWS_EC2_INSTANCE_IP_ADDRESS: ${{ secrets.EC2_IP }}

defaults:
  run:
    working-directory: ./friend-events-apis

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:friend-events-apis"
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > sshconnection.pem && chmod 400 sshconnection.pem

      - name: Pull Docker image
        run: |
          ssh -i "sshconnection.pem" ubuntu@ec2-13-51-85-166.eu-north-1.compute.amazonaws.com 'sudo docker pull ${{ secrets.DOCKERHUB_USER }}/backend:latest'

      - name: Stop running container
        run: |
          ssh -i "sshconnection.pem" ubuntu@ec2-13-51-85-166.eu-north-1.compute.amazonaws.com 'sudo docker stop backend || true'
          ssh -i "sshconnection.pem" ubuntu@ec2-13-51-85-166.eu-north-1.compute.amazonaws.com 'sudo docker rm backend || true'

      - name: Run new container
        run: |
          ssh -i "sshconnection.pem" ubuntu@ec2-13-51-85-166.eu-north-1.compute.amazonaws.com 'sudo docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKERHUB_USER }}/backend:latest'