---
name: Deploy to EC2

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    working-directory: ./friend-events-apis

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:friend-events-apis"
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Install SSH key
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sshconnection.pem && chmod 400 sshconnection.pem

      - name: Pull Docker image
        run: |
          ssh -i sshconnection.pem -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_IP }} 'sudo docker pull ${{ secrets.DOCKERHUB_USER }}/backend:latest'

      - name: Stop running container
        run: |
          ssh -i sshconnection.pem -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_IP }} 'sudo docker stop backend || true'
          ssh -i sshconnection.pem -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_IP }} 'sudo docker rm backend || true'

      - name: Run new container
        run: |
          ssh -i sshconnection.pem -o "StrictHostKeyChecking=no" ubuntu@${{ secrets.EC2_IP }} 'sudo docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKERHUB_USER }}/backend:latest'
