---
name: Lint Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

defaults:
  run:
    working-directory: ./friend-events-apis

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
          
      ######################################################
      # Cache the super-linter action to speed up pipeline #
      ######################################################
      - name: Cache Super-Linter
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/super-linter
          key: super-linter-${{ hashFiles('friend-events-apis/.github/workflows/lint.yml') }}
          restore-keys: |
            super-linter-

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        with:
          EXCLUDED_SCANNERS: javadoc
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
