name: Tests

on:
    push:
      branches:
        - 'master'
    pull_request:
      branches:
        - 'master'

jobs:
    tests:
      runs-on: ubuntu-latest
  
      steps:
        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '17'  # Specify the Java version you need
  
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            path: friend-events-social/friend-events-apis
  
        - name: Clean with Maven
          run: mvn clean --quiet --batch-mode
  
        - name: Build with Maven
          run: mvn install --quiet --batch-mode
  
        - name: Run tests
          run: mvn test --quiet --batch-mode
