name: Tests Pipeline

on:
    push:
      branches:
        - 'master'
    pull_request:
      branches:
        - 'master'

defaults:
  run:
    working-directory: ./friend-events-apis

jobs:
    tests:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: read
        statuses: write
  
      steps:
        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '17'  # Specify the Java version you need
  
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Build with Maven
          run: mvn clean install -DskipTests=true 
  
        - name: Run tests
          run: mvn test --quiet --batch-mode

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
