name: Tests Pipeline

on:
    push:
      branches:
        - 'master'
    pull_request:
      branches:
        - 'master'

defaults:
  run:
    working-directory: ./friend-events-apis

jobs:
    tests:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: read
        statuses: write
  
      steps:
        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '17'  # Specify the Java version you need
  
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Build with Maven
          run: mvn clean install -DskipTests=true 
  
        - name: Run tests
          run: mvn test --quiet --batch-mode

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        - name: Check coverage percentage
          run: |
            coverage=$(curl -s https://codecov.io/gh/${{ github.repository }}/branch/${{ github.ref }}/graphs/sunburst | grep -o -P "(?<= data-label=\"Total\">).*(?=\%<)")
            if [[ $coverage -lt 80 ]]; then
              echo "Coverage is less than 80%."
              exit 1
            else
              echo "Coverage is greater than 80%."
            fi